server:
  port: 8080
  address: 0.0.0.0  # ì™¸ë¶€ ì ‘ê·¼ í—ˆìš© (ë¡œì»¬ í…ŒìŠ¤íŠ¸ìš©)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudpos?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root     # ğŸ‘‰ ë³¸ì¸ MySQL ì•„ì´ë””ë¡œ ë°”ê¿”
    password: suho1234!       # ğŸ‘‰ ë³¸ì¸ MySQL ë¹„ë°€ë²ˆí˜¸ë¡œ ë°”ê¿”

  jpa:
    hibernate:
      ddl-auto: create   # create / update / none ì¤‘ ì„ íƒ (ê°œë°œ ì¤‘ì´ë¼ë©´ update ì¶”ì²œ)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

toss:
  base-url: https://api.tosspayments.com/v2/payments
  client-key: test_ck_ZLKGPx4M3MxGReNMyzww8BaWypv1
  secret-key: test_sk_Z61JOxRQVEokdm9mZZyg8W0X9bAq
  # í”„ë¡ íŠ¸ìš© í‚¤ ë³€ìˆ˜ëª… êµ¬ë¶„ìš©
  widget-client-key: ${toss.client-key}
